### ISSUE TITLE
Snippet rpt does not work

### ISSUE THREAD

**Issue by edvinasjurele** [xabikos/vscode-react#42]
It seems `rpt` snippet does not work for me. Wondering whether it is an issue of my configuration or clash of some other existing configurations.

To reproduce:
![image](https://user-images.githubusercontent.com/9308445/37867030-6912e6a2-2f9b-11e8-825a-224a5c85d8c7.png)

Anyone else facing this issue?

Other snippet works just fine.

Versions:
- VSCode v1.21.1
- Snippets plugin v2.0.0

**Comment by FoxShaunR** [comment]
I'm having the same issue.

Versions:
- VSCode 1.22.0 (1.22.0)
- Same version of the snippets plugin

**Comment by xabikos** [comment]
@eddjoke thanks for reporting this one and I am sorry for the late reply. There is an error indeed because of a forgotten duplicate key in snippets declaration. ([More details](https://github.com/xabikos/vscode-react/blob/master/snippets/snippets.json#L150-L160))
Obviously this was not a problem for previous versions of VS Code but now it is. I have fixed this one. But I am going to wait for a few days to also merge #44 and then publish a new version, if you don't mind.

**Comment by edvinasjurele** [comment]
@xabikos thanks for letting me know. To clarify, which key is a duplicate?

[`rpt`](https://github.com/xabikos/vscode-react/blob/master/snippets/snippets.json#L151) is actually a unique prefix in the snippets.json, but I am wondering if it might clash with something else. That's why I cannot come up with the fix.

**Comment by xabikos** [comment]
@eddjoke `rpt` is indeed unique as prefix. The problem is that in the current version `propTypes` is declared two times. So it's 
```
"propTypes": {
    "prefix": "rpt",
  },
  "propTypes": {
    "prefix": "rdp",
  },
```
This apparently was fine in older versions of VS code but not any more.
